#!/bin/bash

eval "$(conda shell.bash hook)"
conda activate jekyll

python _scripts/addCollection.py

config_file="_config.yml"

if [ -f "$config_file" ]
then 
    rm "$config_file"
fi 

touch _config.yml
cat "_config/others.yml" >> "$config_file"
cat "_config/collections.yml" >> "$config_file"

echo -e "\033[32m_config.yml successfully updated.\033[0m"