#!/bin/bash

config_file="_config.yml"

if [ -f "$config_file" ]
then 
    rm "$config_file"
fi 

touch _config.yml
cat "_config/others.yml" >> "$config_file"
cat "_config/collections.yml" >> "$config_file"

git config user.name "Heekang Park"
git config user.email "park.heekang33@gmail.com"

git add .

time=`date '+%F %H:%M'`
commit_msg="commit from laptop, $time"

if [ -n "$1" ]; then
    commit_msg=$1
fi

git commit -m "$commit_msg"

git push origin master