version: "3.8"
services:
  code-server:
    image: codercom/code-server:latest
    restart: always
    container_name: code-server--blog
    ports:
      - 11110:8080
    volumes:
      - ./.code-server/local:/home/coder/.local
      - ./.code-server/config:/home/coder/.config
      - ./:/home/coder/project
    environment:
      - DOCKER_USER=heekang
    user: 1000:1000

networks:
  default:
    name: code-server--blog